package com.lh.zksocketc.data.DbDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lh.zksocketc.data.model.IcCardNumer;
import com.lh.zksocketc.data.model.WsdData;
import com.lh.zksocketc.data.model.MLsLists;

import com.lh.zksocketc.data.DbDao.IcCardNumerDao;
import com.lh.zksocketc.data.DbDao.WsdDataDao;
import com.lh.zksocketc.data.DbDao.MLsListsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig icCardNumerDaoConfig;
    private final DaoConfig wsdDataDaoConfig;
    private final DaoConfig mLsListsDaoConfig;

    private final IcCardNumerDao icCardNumerDao;
    private final WsdDataDao wsdDataDao;
    private final MLsListsDao mLsListsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        icCardNumerDaoConfig = daoConfigMap.get(IcCardNumerDao.class).clone();
        icCardNumerDaoConfig.initIdentityScope(type);

        wsdDataDaoConfig = daoConfigMap.get(WsdDataDao.class).clone();
        wsdDataDaoConfig.initIdentityScope(type);

        mLsListsDaoConfig = daoConfigMap.get(MLsListsDao.class).clone();
        mLsListsDaoConfig.initIdentityScope(type);

        icCardNumerDao = new IcCardNumerDao(icCardNumerDaoConfig, this);
        wsdDataDao = new WsdDataDao(wsdDataDaoConfig, this);
        mLsListsDao = new MLsListsDao(mLsListsDaoConfig, this);

        registerDao(IcCardNumer.class, icCardNumerDao);
        registerDao(WsdData.class, wsdDataDao);
        registerDao(MLsLists.class, mLsListsDao);
    }
    
    public void clear() {
        icCardNumerDaoConfig.clearIdentityScope();
        wsdDataDaoConfig.clearIdentityScope();
        mLsListsDaoConfig.clearIdentityScope();
    }

    public IcCardNumerDao getIcCardNumerDao() {
        return icCardNumerDao;
    }

    public WsdDataDao getWsdDataDao() {
        return wsdDataDao;
    }

    public MLsListsDao getMLsListsDao() {
        return mLsListsDao;
    }

}
